# Generated by Django 3.2 on 2022-06-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220616_1742'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_recipe',
        ),
    ]
