# Generated by Django 3.2 on 2022-06-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-id',), 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
